# Streamlit Cloud用設定ファイル

# OpenAI API設定
OPENAI_API_KEY = "your_openai_api_key_here"

# 問い合わせメール送信先
INQUIRY_EMAIL_RECIPIENTS = "kenta@ogawara-tosouten.com,ogapen@gmail.com"

# メール送信設定
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = "587"
SMTP_USERNAME = "your_email@gmail.com"
SMTP_PASSWORD = "your_app_password"
